from FoundingTitanRobot import ACKERMANS, TITANSHIFTERS, ROYALS, SCOUTS, GARRISONS, telethn

IMMUNE_USERS = TITANSHIFTERS + GARRISONS + ROYALS + SCOUTS + ACKERMANS

IMMUNE_USERS = (
    list(TITANSHIFTERS) + list(GARRISONS) + list(ROYALS) + list(SCOUTS) + list(ACKERMANS)
)
